# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('color', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=225)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), size=None)),
                ('code', models.CharField(max_length=100)),
                ('numb_of_reviews', models.CharField(blank=True, null=True)),
                ('display_resolution', models.CharField(max_length=100)),
                ('screen_diagonal', models.CharField(max_length=100)),
                ('product_specification', models.JSONField(default=dict)),
            ],
        ),
    ]
